# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lendas-do-asfalto

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ascloud.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_958d6fbfaf2b4d5e98b10eca3593805d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3a261f2722284e0190ba77812b3ac449 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ascloud.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_958d6fbfaf2b4d5e98b10eca3593805d }}/as-cloud-app/as-cloud-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lendas-do-asfalto'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0f1b7e40ed084f22b2c0d4750e45fdd4 }}
        images: 'ascloud.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_958d6fbfaf2b4d5e98b10eca3593805d }}/as-cloud-app/as-cloud-app:${{ github.sha }}'